name: Deploy to MicroK8s

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on:
      - self-hosted
      - ${RUNNER_DEPLOYMENT_NAME}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Harbor
        uses: docker/login-action@v2
        with:
          registry: \${{ secrets.HARBOR_URL }}
          username: \${{ secrets.HARBOR_USERNAME }}
          password: \${{ secrets.HARBOR_PASSWORD }}

      - name: Build and push Docker image
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile # Assumes Dockerfile is at the root
          push: true
          tags: \${{ secrets.HARBOR_URL }}/${HARBOR_PROJECT_NAME}/${HARBOR_IMAGE_NAME}:\${{ github.sha }}
      
          # --- STEP 3: Substitute image tag in manifests ---
      - name: Substitute image tag
        run: |
          find k8s/ -type f -name "*.yaml" -exec sed -i 's|__IMAGE_TAG__|${{ github.sha }}|g' {} +

      # --- STEP 4: Deploy BOTH applications ---
      - name: Deploy to MicroK8s
        uses: azure/k8s-deploy@v4
        with:
          kubeconfig: ${{ secrets.KUBE_CONFIG }}
          action: 'deploy'
          manifests: k8s/
